import type { Metadata } from "next";
import "./globals.css";
import Navigation from "@/components/Navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko-kr">
      <body
        className={`antialiased h-full w-full bg-gradient from-slate-50 via-pink-200 to-purple-100`}
      >
        {children}
        <div className="mt-40">&nbsp;</div>
        <div className="fixed bottom-5 px-5 w-full flex justify-center items-center">
          <Navigation />
        </div>
      </body>
    </html>
  );
}
